main.md and incl.md

diff --git a/hardware-design/Makefile b/hardware-design/Makefile
--- a/hardware-design/Makefile
+++ b/hardware-design/Makefile
@@ -2,51 +2,44 @@
 
 MD2TEX := build/md2tex.py
 
-HOMEWORK_TEX := $(wildcard chapters/*/homework.md)
-HOMEWORK_TEX := $(HOMEWORK_TEX:.md=.gen.tex)
+# some markdown files turn into standalone tex docs
+MD_MAIN := $(shell find * -mindepth 1 -name "*.main.md")
+TEX_MAIN := $(MD_MAIN:.md=.gen.tex)
 
-SLIDES_TEX := $(wildcard chapters/*/slides.md)
-SLIDES_TEX := $(SLIDES_TEX:.md=.gen.tex)
+# some markdown files generate content to be imported
+MD_INCL := $(wildcard chapters/*/*.incl.md)
+MD_INCL := $(MD_INCL:.md=.gen.tex)
+
+# some manual tex docs to import the above
+MANUAL_TEX := $(shell find . -name "*.tex" ! -name "*.gen.*")
+
+PDFS := $(MANUAL_TEX:.tex=.pdf) $(MD_MAIN:.main.md=.pdf)
+
 
 define build_latex
-	@# 1. Determine the source: .gen.tex if it exists, else .tex
-	$(eval SRC := $(shell [ -f $(1).gen.tex ] && echo $(1).gen.tex || echo $(1).tex))
-	@# 2. Extract just the filename (e.g., 'bar' from 'foo/bar')
 	$(eval BASE := $(notdir $(1)))
-	@# 3. Extract the directory (e.g., 'foo' from 'foo/bar')
-	$(eval DIR := $(or $(dir $(1)), .))
-	@printf "\033[35mbuilding $(1).pdf from $(SRC)... \033[0m"
-	@# -cd changes to the directory of the file
-	@# -jobname=$(BASE) ensures it's 'bar.pdf' even if input is 'bar.gen.tex'
-	@latexmk -silent -pdf -jobname=$(BASE) -interaction=nonstopmode -shell-escape -cd $(SRC) >/dev/null ; \
+	@printf "\033[35mbuilding $(1).pdf from $(2)... \033[0m"
+	@latexmk -silent -pdf -jobname=$(BASE) -interaction=nonstopmode -shell-escape -cd $(2) >/dev/null 2>&1; \
 	if [ -f $(1).pdf ]; then \
-        printf "\033[92mdone\033[0m\n"; \
-		latexmk -c -jobname=$(BASE) -cd -e '$$clean_ext = "nav snm vrb"' $(SRC) >/dev/null; \
+		printf "\033[92mdone\033[0m\n"; \
+		latexmk -c -jobname=$(BASE) -cd -e '$$clean_ext = "nav snm vrb"' $(2) >/dev/null 2>&1; \
 	else \
-		echo "\033[31mfailed\033[0m (see $(1).log)"; \
-		cat $(1).log; exit 1; \
+		printf "\033[31mfailed\033[0m (see $(1).log)\n"; \
+		[ -f $(1).log ] && cat $(1).log; exit 1; \
 	fi
 endef
 
 
+all: $(PDFS)
 
+%.pdf: %.tex $(INCL_TEX)
+	@$(call build_latex,$*,$<)
 
-
-
-
-all: syllabus/syllabus.pdf homework.pdf slides.pdf 
-
-homework.pdf: homework.tex $(HOMEWORK_TEX)
-	@ $(call build_latex,homework)
-
-slides.pdf: slides.tex $(SLIDES_TEX)
-	@ $(call build_latex,slides)
-
-syllabus/syllabus.pdf: syllabus/syllabus.gen.tex
-	@ $(call build_latex,syllabus/syllabus)
+%.pdf: %.main.gen.tex
+	@$(call build_latex,$*,$<)
 
 %.gen.tex: %.md $(MD2TEX)
-	@ $(MD2TEX) $<
+	@$(MD2TEX) $<
 
 # remove junk per the .gitignore
 clean: tidy
